// Plain-language names for audit log entries, and the shapes the viewer receives.
import { z } from 'zod'

export const ACTION_LABELS: Record<string, string> = {
  'auth.signIn': 'Signed in',
  'account.create': 'Created account',
  'account.roles': 'Changed roles',
  'account.block': 'Blocked account',
  'account.unblock': 'Unblocked account',
  'account.delete': 'Deleted account',
  'account.passwordLink': 'Sent password link',
  'account.signOutEverywhere': 'Signed account out everywhere',
  'account.link': 'Connected account to person',
  'account.unlink': 'Disconnected account from person',
  'person.create': 'Added person',
  'person.update': 'Edited person',
  'person.delete': 'Removed person',
  'privacy.update': 'Changed sharing',
  'profile.update': 'Updated own profile',
  'household.create': 'Added household',
  'household.update': 'Edited household',
  'household.delete': 'Removed household',
  'ministry.create': 'Added ministry',
  'ministry.update': 'Edited ministry',
  'ministry.delete': 'Removed ministry',
  'sermon.create': 'Added sermon',
  'sermon.update': 'Edited sermon',
  'sermon.publish': 'Published sermon',
  'sermon.unpublish': 'Unpublished sermon',
  'sermon.delete': 'Removed sermon',
  'series.create': 'Added series',
  'series.update': 'Edited series',
  'series.delete': 'Removed series',
  'speaker.add': 'Added speaker',
  'speaker.update': 'Edited speaker',
  'speaker.archive': 'Archived speaker',
  'speaker.restore': 'Restored speaker',
  'speaker.delete': 'Permanently removed speaker',
  'missionary.create': 'Added missionary',
  'missionary.update': 'Edited missionary',
  'missionary.archive': 'Archived missionary',
  'missionary.restore': 'Restored missionary',
  'missionary.delete': 'Permanently removed missionary',
  'missionary.prayerRequest': 'Added prayer request',
  'missionary.letter': 'Added prayer letter',
  'missionary.updateRemoved': 'Removed a prayer request or letter',
  'missionOrganization.create': 'Added mission organization',
  'missionOrganization.update': 'Edited mission organization',
  'missionOrganization.archive': 'Archived mission organization',
  'missionOrganization.restore': 'Restored mission organization',
  'missionOrganization.delete': 'Permanently removed mission organization',
  // Stewardship. Entries name what changed, never amounts, payees or bank wording.
  'financeAccount.create': 'Added budget account',
  'financeAccount.update': 'Edited budget account',
  'financeAccount.archive': 'Archived budget account',
  'financeAccount.restore': 'Restored budget account',
  'sync.run': 'Checked the bank',
  'transaction.create': 'Added transaction',
  'transaction.update': 'Edited transaction',
  'transaction.categorize': 'Categorized transaction',
  'transaction.delete': 'Removed transaction',
  'rule.create': 'Added payee rule',
  'rule.update': 'Edited payee rule',
  'rule.delete': 'Removed payee rule',
  'categoryGroup.create': 'Added category group',
  'categoryGroup.update': 'Edited category group',
  'categoryGroup.archive': 'Archived category group',
  'categoryGroup.restore': 'Restored category group',
  'categoryGroup.delete': 'Removed category group',
  'category.create': 'Added category',
  'category.update': 'Edited category',
  'category.archive': 'Archived category',
  'category.restore': 'Restored category',
  'category.delete': 'Removed category',
  'budget.fund': 'Changed category funding',
  'ministryAccess.grant': 'Gave a ministry budget access',
  'ministryAccess.change': 'Changed a ministry’s budget access',
  'ministryAccess.revoke': 'Removed a ministry’s budget access',
  'plan.set': 'Set a category plan',
  'plan.remove': 'Removed a category plan',
  'budget.fundPlans': 'Funded plans',
  'recurring.create': 'Added recurring transaction',
  'recurring.update': 'Edited recurring transaction',
  'recurring.archive': 'Archived recurring transaction',
  'recurring.restore': 'Restored recurring transaction',
  'recurring.delete': 'Removed recurring transaction',
  'recurring.skip': 'Skipped a recurring transaction',
  // Giving. Never amounts, giver names or email addresses.
  'giver.create': 'Added giving record',
  'giver.update': 'Edited giving record',
  'giver.archive': 'Archived giving record',
  'giver.restore': 'Restored giving record',
  'giver.delete': 'Removed giving record',
  'count.open': 'Started offering count',
  'count.update': 'Edited offering count',
  'count.close': 'Closed offering count',
  'count.reopen': 'Reopened offering count',
  'count.linkDeposit': 'Linked count to its deposit',
  'count.unlinkDeposit': 'Unlinked count from its deposit',
  'gift.add': 'Entered a gift',
  'gift.update': 'Edited a gift',
  'gift.remove': 'Removed a gift',
  'statementSettings.update': 'Edited statement settings',
  'statement.send': 'Emailed giving statements',
  'statement.print': 'Printed giving statements',
  'report.export': 'Downloaded a semi-annual report',
}

export const ENTITY_TYPE_LABELS: Record<string, string> = {
  user: 'Accounts',
  person: 'People',
  household: 'Households',
  ministry: 'Ministries',
  sermon: 'Sermons',
  sermonSeries: 'Sermon series',
  missionary: 'Missionaries',
  missionOrganization: 'Mission organizations',
  financeAccount: 'Budget accounts',
  syncRun: 'Bank checks',
  transaction: 'Transactions',
  payeeRule: 'Payee rules',
  categoryGroup: 'Category groups',
  category: 'Categories',
  budget: 'Budget',
  recurring: 'Recurring transactions',
  giver: 'Giving records',
  count: 'Offering counts',
  statement: 'Giving statements',
  report: 'Reports',
}

export const actionLabel = (action: string) => ACTION_LABELS[action] ?? action

export const auditQuerySchema = z.object({
  page: z.coerce.number().int().min(1).max(10_000).default(1),
  pageSize: z.coerce.number().int().min(10).max(200).default(50),
  entityType: z.string().max(40).optional(),
  action: z.string().max(60).optional(),
  actorId: z.string().max(100).optional(),
  // Inclusive dates, YYYY-MM-DD, in the server's time zone.
  from: z.iso.date().optional(),
  to: z.iso.date().optional(),
  // Hide sign-ins, which otherwise crowd out changes.
  hideSignIns: z.enum(['true', 'false']).default('false').transform(value => value === 'true'),
})

export interface AuditEntryView {
  id: string
  at: string
  action: string
  entityType: string
  entityId: string | null
  // A name for what was changed, or null if it no longer exists.
  entityLabel: string | null
  actor: { id: string, label: string } | null
  fields: string[]
  note: string | null
}
